CRUDExample/CRUDExample/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace CRUDExample.Controllers
{
    [Route("[controller]")]
    public class CountriesController : Controller
    {
        private ICountriesService _countriesService;

        public CountriesController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult UploadFromExcel()
        {
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file!";
                return View();
            }

            if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx",StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported file, 'xlsx' file is expected!";
                return View();
            }

            int countriesCountInserted = await _countriesService.UploadCountriesFromExcelFile(excelFile);

            ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
            return View();
        }
    }
}

CRUDExample/CRUDExample/Views/Shared/_GridColumnHeader.cshtml
@if (ViewBag.CurrentSortBy == (ViewBag.ColumnName) && ViewBag.CurrentSortOrder == (nameof(SortOrderOptions.ASC)))
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(SortOrderOptions.DESC)">
            @ViewBag.DisplayName
        </a>
        <i class="fa-solid fa-sort-up"></i>
    </th>
}
else if (ViewBag.CurrentSortBy == (ViewBag.ColumnName) && ViewBag.CurrentSortOrder == (nameof(SortOrderOptions.DESC)))
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(SortOrderOptions.ASC)">
            @ViewBag.DisplayName
        </a>
        <i class="fa-solid fa-sort-down"></i>
    </th>
}
else@*如果排序字段是其它字段*@
{
    <th>
        <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(SortOrderOptions.ASC)">
            @ViewBag.DisplayName
        </a>
    </th>
}

CRUDExample/CRUDExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/stylesheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container">
        <div class="page-content">
            <div class="margin-bottom">
                <div class="flex" id="top-bar-div">
                    <div class="flex-1" id="app-title-div">
                        <h1 class="app-title">
                            <i class="fa-solid fa-people-simple"></i>
                            Contact Manager
                        </h1>
                    </div>
                    <div class="flex-1 pr" id="search-box-div">
                        <div class="navbar account-links">
                            <ul>
                                <li>
                                    <a asp-controller="Account" asp-action="Register">Register</a>
                                    <a asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar mb">
                <ul>
                    <li>
                        <a asp-controller="Persons" asp-action="Index">Persons</a>
                        <a asp-controller="Countries" asp-action="UploadFromExcel">Upload Countries</a>
                    </li>
                </ul>
            </div>

            <div class="body">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderSection("scripts", false)
</body>
</html>